global:
  scrape_interval: 2s
  evaluation_interval: 2s
scrape_configs:
  - job_name: 'app-api'
    metrics_path: '/app/actuator/prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: ['local-app-api:8080']
  - job_name: 'user-api'
    metrics_path: '/user/actuator/prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: [ 'local-user-api:8081' ]
